###
# curl -i -X POST http://localhost:8080/restapi/batch-jobs/batchletEnforcementZoneCentre
POST http://localhost:8080/restapi/batch-jobs/batchletEnforcementZoneCentre

###

# curl -i -X POST http://localhost:8080/restapi/batch-jobs/chunkEnforcementZoneCentreCsvToSqlScriptFile
POST http://localhost:8080/restapi/batch-jobs/chunkEnforcementZoneCentreCsvToSqlScriptFile

###

# curl -i -X POST http://localhost:8080/restapi/batch-jobs/chunkEnforcementZoneCentreImportCsvToDatabase
POST http://localhost:8080/restapi/batch-jobs/chunkEnforcementZoneCentreImportCsvToDatabase

###
# curl -i -X GET http://localhost:8080/restapi/batch-jobs/1
GET http://localhost:8080/restapi/batch-jobs/3

###
# curl -i -X POST http://localhost:8080/restapi/batch-jobs/batchletETLProcessForDWPubsSales
POST http://localhost:8080/restapi/batch-jobs/batchletETLProcessForDWPubsSales

###




